---
version: 2
formats: all
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv run --frozen --all-extras --group=docs pdoc -d google -t pdoc-template --math -o _readthedocs/html/ arguebuf
    - cp -rf ./assets ./_readthedocs/html/
