on:
  pull_request:
  push:
    branches:
      - main
      - beta
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GH_PULL_CREDENTIALS }}
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v3
      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "git@github.com:"
          replace: "https://github.com/"
          regex: false
          include: "**/*.dvc"
      - uses: iterative/setup-dvc@v1
        with:
          version: "2.58.2"
      - run: dvc pull --force
      - run: nix develop -c poetry run pytest
  release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.repository_owner == 'recap-utr' && github.event_name == 'push' }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v3
      - run: nix profile install .#releaseEnv
      - uses: cihelper/action-semanticrelease-poetry@v1
        id: semanticrelease
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
